### ISSUE TITLE
Support @typescript-eslint/eslint-plugin for script templates

### ISSUE THREAD

**Issue by yusufkandemir** [ota-meshi/eslint-plugin-lodash-template#226] opened 2022-03-19 17:33 UTC
### Explanation

> 6:9  error  Parsing error: Unexpected token module  lodash-template/no-script-parsing-error

```ts
// ...

declare module /* <--- Error happens here */ 'vue/types/vue' {
  <% if (preset.lint && lintConfig === 'airbnb') { %>// eslint-disable-next-line no-shadow<% } %>
  interface Vue {
    i18n: VueI18n;
  }
}
```

It looks like it's not correctly using `@typescript-eslint/parser`. I am not sure if it is supposed to support TS at all. So, this might be a bug or a feature request.

The error doesn't happen if there are no template delimiters in TS files. My guess is that it is happening during the template delimiters embedding operation: https://github.com/ota-meshi/eslint-plugin-lodash-template/blob/master/lib/parser/parse-template-script/embed-interpolations.js

### Config

```js
overrides: [
  {
    files: './templates/*/*/*/**/*.ts',
    
    parserOptions: {
      parser: '@typescript-eslint/parser',
      sourceType: 'module'
    },

    env: {
      browser: true,
    },

    extends: [
      'plugin:@typescript-eslint/recommended',
      'plugin:lodash-template/recommended-with-script'
    ],
  },
],
```
Related parts from the output of `eslint --print-config ./correct/path/to/related/file.ts`:
```json
"parser": "/correct/absolute/path/node_modules/eslint-plugin-lodash-template/lib/parser/micro-template-eslint-parser.js",
"parserOptions": {
  "parser": "@typescript-eslint/parser",
  "sourceType": "module"
},
"plugins": [
  "@typescript-eslint",
  "lodash-template"
],
```
So, it picks up the `micro-template-eslint-parser`, which then uses `@typescript-eslint/parser` as the "sub" parser, similar to `eslint-plugin-vue` I guess, according to what I understood from the source code.

**Comment by ota-meshi** [comment] 2022-03-20 01:18
Thank you for posting issue.

The plugin does not use `parserOptions.parser` for script parsers outside of scriptlets.

To specify a parser outside the scriptlet, you need to specify the parser to apply to the `eslint-plugin-lodash-template-${prefix}${index}.js` file.

https://github.com/ota-meshi/eslint-plugin-lodash-template/blob/master/lib/processors/script/index.js#L215-L225

Maybe you need to configure it like this:

```js
overrides: [
  {
    files: './templates/*/*/*/**/*.ts',
    extends: [
      'plugin:lodash-template/recommended-with-script'
    ],
  },
  {
    files: './templates/*/*/*/**/*.js',

    parser: '@typescript-eslint/parser',
    parserOptions: {
      sourceType: 'module'
    },
    env: {
      browser: true,
    },

    extends: [
      'plugin:@typescript-eslint/recommended'
    ],
  },
],
```

**Comment by yusufkandemir** [comment] 2022-03-20 08:14
Thanks for the quick answer and great plugin.

When I applied your suggestion, I started getting `1:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'` errors on `.ts` files. So, I also added `sourceType: 'module'` to the `*.ts` overrides section. Those errors naturally went away, but I started getting crazy amounts of parsing errors such as:
> 1:8  error  Parsing error: Unexpected token interface

> 3:0  error  Parsing error: Expression expected

> 3:13  error  Parsing error: Unexpected token :

An example file that gets errors:
```ts
export interface Todo {
  id: number;
  content: string;
}

export interface Meta {
  totalCount: number;
}
```
as you can see, it's a plain TS file. But, it gets parsing errors.

I also tried adding a new override with the file name format you've sent, but it didn't change anything.
```js
{
  files: '**/eslint-plugin-lodash-template-*.js',
  
  parser: '@typescript-eslint/parser',
  parserOptions: {
    sourceType: 'module'
  },

  env: {
    browser: true,
  },

  extends: [
    'plugin:@typescript-eslint/recommended'
  ],
},
```

**Comment by yusufkandemir** [comment] 2022-03-20 08:26
I've found that when using my initial config, it actually works most of the time. An example case where it is working:
```ts
import { route } from 'quasar/wrappers';
import {
  createMemoryHistory,
  createRouter,
  createWebHashHistory,
  createWebHistory,
} from 'vue-router';
<% if (preset.vuex) { %>import { StateInterface } from '../store';
<% } %>
import routes from './routes';

/*
 * If not building with SSR mode, you can
 * directly export the Router instantiation;
 *
 * The function below can be async too; either use
 * async/await or return a Promise which resolves
 * with the Router instance.
 */

export default route<% if (preset.vuex) { %><StateInterface><% } %>(function (/* { store, ssrContext } */) {
  const createHistory = process.env.SERVER
    ? createMemoryHistory
    : (process.env.VUE_ROUTER_MODE === 'history' ? createWebHistory : createWebHashHistory);

  const Router = createRouter({
    scrollBehavior: () => ({ left: 0, top: 0 }),
    routes,

    // Leave this as is and make changes in quasar.conf.js instead!
    // quasar.conf.js -> build -> vueRouterMode
    // quasar.conf.js -> build -> publicPath
    history: createHistory(process.env.VUE_ROUTER_BASE),
  });

  return Router;
});
```
as you can see it's a TS file and contains template delimiters and gets parsed/process/linted correctly.

Here is my full config for reference:
```ts
module.exports = {
  root: true,

  env: {
    node: true,
    es2020: true,
  },

  extends: [
    'eslint:recommended',
  ],

  rules: {
    'no-empty': 'off',
    'no-unused-vars': 'off',
  },

  settings: {
    'lodash-template/ignoreRules': ['no-undef']
  },

  overrides: [
    {
      files: './templates/*/*/*/**/*.ts',
      parserOptions: {
        parser: '@typescript-eslint/parser',
        sourceType: 'module'
      },
      extends: [
        'plugin:@typescript-eslint/recommended',
        'plugin:lodash-template/recommended-with-script'
      ],
    },

    {
      files: './templates/*/*/*/**/*.js',

      parserOptions: {
        sourceType: 'module'
      },

      env: {
        browser: true,
      },

      extends: [
        'plugin:lodash-template/recommended-with-script'
      ],
    },

    {
      files: './templates/ui-kit/quasar-v2/**/*.js',
      
      globals: {
        __UI_VERSION__: 'readonly',
      }
    }
  ]
}
```
I am using it in https://github.com/quasarframework/quasar/tree/dev/create-quasar, though it's all on my local because I couldn't get everything to work yet. But, I thought seeing the project and the file structure might help, it can also serve as a base for repro. I can also share my current mostly working, partly malfunctioning configuration if you need it.

The only problem is the one I mentioned in the issue description. Even though it can parse and process other files, when it gets to the code below, it can't handle it.
```ts
declare module /* <--- Error happens here */ 'vue/types/vue' {
  <% if (preset.lint && lintConfig === 'airbnb') { %>// eslint-disable-next-line no-shadow<% } %>
  interface Vue {
    i18n: VueI18n;
  }
}
```

I've found this plugin really useful even though I couldn't get it to fully function on my setup. So, thank you again for creating and maintaining great ESLint plugins like this, the Vue one, etc.

**Comment by ota-meshi** [comment] 2022-03-22 01:22
Thank you for sharing the repository. I checked it.

Sorry. I gave you the wrong information.

> The plugin does not use `parserOptions.parser` for script parsers outside of scriptlets.

Parsing the outside of the scriptlet also had to use the parser built into the plugin. That is, you should also use `parserOptions.parser`.
(I remembered it wrong because I was away from this repo for a long time 😓 )

Given these, you need to use a configuration like this:

```js
    overrides: [
        {
            files: './templates/*/*/*/**/*.ts',
            parserOptions: {
                parser: '@typescript-eslint/parser',
                sourceType: 'module'
            },
            extends: [
                'plugin:@typescript-eslint/recommended',
                'plugin:lodash-template/recommended-with-script'
            ],
        },
        {
            files: './templates/*/*/*/**/*.js',
            parserOptions: {
                parser: '@typescript-eslint/parser',
                sourceType: 'module'
            },
            extends: [
                'plugin:@typescript-eslint/recommended',
                'plugin:lodash-template/recommended-with-script'
            ],
        },
```

This is necessary because the virtually generated file name is fixed in `.js`.
I need to modify this plugin to control the virtual file extension not to change.

I think it may not be necessary to override `.js` if the plugin changes.

**Comment by yusufkandemir** [comment] 2022-03-22 09:42
Ah, great, thank you for the explanation. That works as you said.

The equivalent configuration in a simpler form:
```js
overrides: [
  {
    files: './templates/*/*/*/**/*.{js,ts}',
    parserOptions: {
        parser: '@typescript-eslint/parser',
        sourceType: 'module'
    },
    extends: [
        'plugin:@typescript-eslint/recommended',
        'plugin:lodash-template/recommended-with-script'
    ],
  },
]
```

I needed to do a lot more overrides to actually distinguish the actual TS and JS files. If it preserves the original extension as you said, this would become so much easier.

I noticed a small problem. In the code below(_a `.js` file_), `path` is imported on top, and used like `path.resolve` on the bottom. But, it gives this warning: `14:31  warning  'path' is assigned a value but never used  no-unused-vars`. So, it can't detect that it gets used. I tried it without TypeScript ESLint, the result is the same. Is this a known limitation, if not do you know what can be the problem?
```js
// ...
<% if (preset.lint && lintConfig === 'airbnb') { %>/* eslint func-names: 0 */
/* eslint global-require: 0 */<% } %>
const { configure } = require('quasar/wrappers');
<% if (preset.i18n) { %>const path = require('path');<% } %>

module.exports = configure(function (/* ctx */) {
  return {
    <% if (preset.lint) { %>eslint: {
      // fix: true,
      // include = [],
      // exclude = [],
      // rawOptions = {},
      warnings: true,
      errors: true
    },<% } %>

    // https://v2.quasar.dev/quasar-cli/prefetch-feature
    // preFetch: true,

    // app boot file (/src/boot)
    // --> boot files are part of "main.js"
    // https://v2.quasar.dev/quasar-cli/boot-files
    boot: [
      <% if (preset.i18n) { %>'i18n',<% } %>
      <% if (preset.axios) { %>'axios',<% } %>
    ],

    // https://v2.quasar.dev/quasar-cli-vite/quasar-config-js#css
    css: [
      'app.<%= css %>'
    ],

    // https://github.com/quasarframework/quasar/tree/dev/extras
    extras: [
      // 'ionicons-v4',
      // 'mdi-v5',
      // 'fontawesome-v6',
      // 'eva-icons',
      // 'themify',
      // 'line-awesome',
      // 'roboto-font-latin-ext', // this or either 'roboto-font', NEVER both!

      'roboto-font', // optional, you are not bound to it
      'material-icons', // optional, you are not bound to it
    ],

    // Full list of options: https://v2.quasar.dev/quasar-cli-vite/quasar-config-js#build
    build: {
      target: {
        browser: [ 'es2019', 'edge88', 'firefox78', 'chrome87', 'safari13.1' ],
        node: 'node16'
      },

      vueRouterMode: 'hash', // available values: 'hash', 'history'
      // vueRouterBase,
      // vueDevtools,
      // vueOptionsAPI: false,

      // rebuildCache: true, // rebuilds Vite/linter/etc cache on startup

      // publicPath: '/',
      // analyze: true,
      // env: {},
      // rawDefine: {}
      // ignorePublicFolder: true,
      // minify: false,
      // polyfillModulePreload: true,
      // distDir

      // extendViteConf (viteConf) {},
      // viteVuePluginOptions: {},

      <% if (preset.i18n) { %>vitePlugins: [
        ['@intlify/vite-plugin-vue-i18n', {
          // if you want to use Vue I18n Legacy API, you need to set `compositionOnly: false`
          // compositionOnly: false,

          // you need to set i18n resource including paths !
          include: path.resolve(__dirname, './src/i18n/**')
        }]
      ]<% } else { %>
      // vitePlugins: [
      //   [ 'package-name', { ..options.. } ]
      // ]<% } %>
    },
// ...
```

**Comment by ota-meshi** [comment] 2022-03-23 00:50
I didn't know the limitation. But I think I can explain the possible causes.

This plugin parses script templates by splitting them into multiple script ASTs and merging those reports to produce results.

For example, the following script will generate three script ASTs.

Input: 

```js
const a = 'foo'
<% if (x) { %>
  const b = 1;
<% } else { %>
  const b = 2;
<% } %>
```

For Scriptlet AST:

```js

   if (x) { 

   } else { 

   }
```

For Script AST (1 :
```js
const a = 'foo'

  const b = 1;



```

For Script AST (2 :

```js
const a = 'foo'



  const b = 2;

```

This is because if we simply try to generate an AST that strips the scriptlet, we will get a parse error.
To prevent parsing errors, the plugin creates multiple scripts that can cover each branch at least once if it has an `if` statement with an `else` and a `switch` statement.

This method does not successfully suppress the reporting of your script. This is because it creates multiple scripts as follows.

Input: 

```js
<% if (x) { %>
  import path from 'path'
<% } %>
// ... main process
<% if (x) { %>
  path.resolve('./foo')
<% } else { %>
  // ... else process
<% } %>
```

For Scriptlet AST:

```js
   if (x) {

   }

   if (x) {

   } else {

   } %>
```

For Script AST (1 :
```js

  import path from 'path'

// ... main process

  path.resolve('./foo')



```

For Script AST (2 :

```js

  import path from 'path'

// ... main process



  // ... else process

```

`(2` script gives a warning that `path` is not used.

To solve it, we need to parse more in the `if` statement of the scriptlet and reproduce the template that is actually used, but it can be quite difficult.

**Comment by ota-meshi** [comment] 2022-03-23 01:20
I released v0.20.0 and changed it to keep the extension (.ts). #230
Can you try using it and see if it works?

**Comment by yusufkandemir** [comment] 2022-03-23 12:47
Thank you for the release 🚀 Distinguishing JS and TS files work correctly now. Maybe some text explaining the [TypeScript ESLint](https://typescript-eslint.io/) support into the README would be nice for others.

The explanation of the parsing process is really clear now, great explanation 👏. As you said, it sounds like it needs a more complicated solution to properly relate and handle related branches. It's not a big deal ATM. Although the warnings are annoying, I will keep the rule to spot possible new problems. A feature like this could be cool though. It might be also wise to document this behavior.

**Comment by ota-meshi** [comment] 2022-03-24 01:05
> Maybe some text explaining the [TypeScript ESLint](https://typescript-eslint.io/) support into the README would be nice for others.

Thank you for your suggestion! I think it's good to add to docs about how to use it with TypeScript templates, as you say. I added it :+1:

> As you said, it sounds like it needs a more complicated solution to properly relate and handle related branches. 

I am working on improving this problem a bit.
It is difficult to compare the AST of the conditions, so I will try to compare the conditions on a text basis. I think we can probably solve some problems.

**Comment by ota-meshi** [comment] 2022-03-24 07:18
I released v0.21.0.
Can you try using it and see if it works?

**Comment by yusufkandemir** [comment] 2022-03-24 08:04
Wow 🔥 no more false positives. Thank you for your quick support 👏

**Closed** 2022-03-24 08:11 UTC

**Comment by ota-meshi** [comment] 2022-03-24 08:19
Thank you for let me know!
This plugin has become more functional thanks to you sharing a lot of information. If you have any other issues, feel free to open the new issue.
